FROM golang:alpine

ENV PORT=8080

WORKDIR /go/src/app

# use cache
COPY src/go.mod .
COPY src/go.sum .

COPY src .

# live reload
RUN go get github.com/cespare/reflex

# Run the two commands below to install git and dependencies for the project. 
RUN apk update && apk add --no-cache git
RUN go get -d -v ./...

CMD reflex -r '\.go' -s -- sh -c "go run main.go"
