FROM golang:alpine

ENV GIN_MODE=release
ENV PORT=8080

WORKDIR /go/src/app

COPY src/go.mod .
COPY src/go.sum .
COPY src .

# Run the two commands below to install git and dependencies for the project. 
RUN apk update && apk add --no-cache git
RUN go get -d -v ./...

RUN go build -o app

ENTRYPOINT ["./app"]
